name: nak_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/json/chapters.json
    - assets/json/dues.json
    - assets/json/board_members.json

  fonts:
    - family: TrajanPro
      fonts:
        - asset: assets/fonts/TrajanPro-Regular.ttf
        - asset: assets/fonts/TrajanPro-Bold.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura Condensed Extra Bold.otf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue Light.ttf
    - family: College
      fonts:
        - asset: assets/fonts/college.ttf
