name: nak_app
description: "The official NAK app."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
# Example: flutter build appbundle --build-name=0.1.8+2 --build-number=2
version: 0.1.34
# version: 0.1.34+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.5
  firebase_analytics: ^10.10.0
  firebase_auth: ^4.17.9
  firebase_core: ^2.32.0
  firebase_storage: ^11.6.11
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.2
  flutter_speed_dial: ^7.0.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  mailer: ^6.1.0
  markdown_widget: ^2.3.2+6
  qr_flutter: ^4.1.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

# use <dart run flutter_launcher_icons> to generate
# icons (from 1024x1024 image in image_path)
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icons/nak_icon.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/chapters/
    - assets/img/carousel/
    - assets/img/stories/
    - assets/img/users/
    - assets/img/title_thumbnails/
    - assets/img/resource_thumbnails/
    - assets/img/id/
    - assets/img/bg/
    - assets/json/chapters.json
    - assets/json/dues.json
    - assets/json/board_members.json
    - assets/docs/

  fonts:
    - family: TrajanPro
      fonts:
        - asset: assets/fonts/TrajanPro-Regular.ttf
        - asset: assets/fonts/TrajanPro-Bold.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura Condensed Extra Bold.otf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue Light.ttf
    - family: College
      fonts:
        - asset: assets/fonts/college.ttf
        - asset: assets/fonts/collegeb.ttf
          weight: 700
    - family: Clarendon
      fonts:
        - asset: assets/fonts/Clarendon LT Regular.ttf
    - family: LuloClean
      fonts:
        - asset: assets/fonts/Lulo Clean One Bold.otf
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: "Oswald"
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 700
    - family: "Bebas"
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: "SpaceMono"
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: "Diatype"
      fonts:
        - asset: assets/fonts/ABCDiatypeMono-Regular-Trial.otf
        - asset: assets/fonts/ABCDiatypeMono-Medium-Trial.otf
          weight: 700
