name: nak_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  date_picker_timeline: ^1.2.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.18.1
  mailer: ^6.1.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

# use <dart run flutter_launcher_icons> to generate
# icons (from 1024x1024 image in image_path)
flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/img/icons/nak_icon.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/chapters/
    - assets/img/carousel/
    - assets/img/stories/
    - assets/img/users/
    - assets/img/title_thumbnails/
    - assets/img/resource_thumbnails/
    - assets/img/id/
    - assets/json/chapters.json
    - assets/json/dues.json
    - assets/json/board_members.json

  fonts:
    - family: TrajanPro
      fonts:
        - asset: assets/fonts/TrajanPro-Regular.ttf
        - asset: assets/fonts/TrajanPro-Bold.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura Condensed Extra Bold.otf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue Light.ttf
    - family: College
      fonts:
        - asset: assets/fonts/college.ttf
        - asset: assets/fonts/collegeb.ttf
          weight: 700
    - family: Clarendon
      fonts:
        - asset: assets/fonts/Clarendon LT Regular.ttf
    - family: LuloClean
      fonts:
        - asset: assets/fonts/Lulo Clean One Bold.otf
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: "Oswald"
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 700
    - family: "Bebas"
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
